#!/bin/bash
# Create the DocsGPT build issues for Atlas + the team
ssh -o BatchMode=yes -o ConnectTimeout=10 -i ~/.ssh/id_nura_clean root@72.60.163.140 'docker exec paperclip-db psql -U paperclip -d paperclip <<EOF
INSERT INTO issues (company_id, title, description, status, priority) VALUES
('"'"'58ddc931-7dbb-44c3-ab34-2652571121fc'"'"', '"'"'DOCSGPT-1: Medical corpora ingestion'"'"', '"'"'Ingest the medical corpus (Lab /opt/nura-corpora/textbooks — 18 pre-chunked JSONL files, 202MB) into the DocsGPT sources (Clinic /docker/docsgpt, backend :7091). Use the docs-upload/source-creation lane; verify the answer cites the textbooks. Acceptance: "What is anatomy?" returns the textbook-grounded answer with the source metadata. Agent key: ${DOCSGPT_API_KEY:-REDACTED}. Founder directive 08-06: build all of DocsGPT.'"'"', '"'"'todo'"'"', '"'"'high'"'"'),
('"'"'58ddc931-7dbb-44c3-ab34-2652571121fc'"'"', '"'"'DOCSGPT-2: Chatwoot bridge deploy'"'"', '"'"'Deploy the official Chatwoot extension (DocsGPT/extensions/chatwoot — HMAC webhook → /api/answer → reply via api_access_token; label human-requested = stop). Acceptance: a Chatwoot conversation gets the DocsGPT reply end-to-end. The generic bridge (chatwoot-bridge.py :8790 → Perfex/OpenEMR drafts) stays separate.'"'"', '"'"'todo'"'"', '"'"'high'"'"'),
('"'"'58ddc931-7dbb-44c3-ab34-2652571121fc'"'"', '"'"'DOCSGPT-3: Public door + auth'"'"', '"'"'Wire the public door (docs.nuratech.ai or similar via NPM on the Clinic — host + letsencrypt cert + the Hostinger firewall rule-sync per the api-gateway-public-fix skill) AND the user-auth gates (the app auth-mode + roles — no open internet exposure without auth). Acceptance: https door 200 + the auth-protected lanes.'"'"', '"'"'todo'"'"', '"'"'high'"'"'),
('"'"'58ddc931-7dbb-44c3-ab34-2652571121fc'"'"', '"'"'DOCSGPT-4: Langfuse tracing wiring'"'"', '"'"'Wire the Langfuse tracing (Clinic :3020 — the ingestion keys + the SDK env) into the DocsGPT backend so every answer is auditable. Acceptance: an answer produces a visible trace in Langfuse with the model/prompt versions.'"'"', '"'"'todo'"'"', '"'"'medium'"'"'),
('"'"'58ddc931-7dbb-44c3-ab34-2652571121fc'"'"', '"'"'DOCSGPT-5: LiteLLM gateway integration'"'"', '"'"'Add the LiteLLM gateway lane for the DocsGPT model routing (the sovereign Ollama default + the fallback tiers per the nura-gateway-routing-architecture skill). Acceptance: the /api/answer routes via LiteLLM with the cost/latency logged.'"'"', '"'"'todo'"'"', '"'"'medium'"'"')
RETURNING title, status;
EOF'
