#!/usr/bin/env python3
"""Generate NURA stack inventory (skills, lanes, providers, crons, docs, board) for external review."""
import json, os, re, glob, shutil
from pathlib import Path

OUT = []
def p(s=""): OUT.append(s)

P = Path("/opt/data/profiles/nura")
count = len(list(P.joinpath("skills").rglob("SKILL.md")))

p("# NURA OS — INSTALLED STACK INVENTORY (2026-08-02)")
p("_Generated by Hermes. Shareable with Gemini for suggestions._")
p("")
p("## 1. Skills: " + str(count) + " total")
cats = {}
for f in P.joinpath("skills").rglob("SKILL.md"):
    rel = f.relative_to(P.joinpath("skills"))
    cat = rel.parts[0] if len(rel.parts) > 1 else "(root)"
    name = rel.parts[-2] if len(rel.parts) > 1 else f.stem
    cats.setdefault(cat, []).append(name)
for c in sorted(cats):
    p("")
    p("### " + c + " (" + str(len(cats[c])) + ")")
    p(", ".join(sorted(cats[c])))

# 2. MCP lanes
lanes = []
try:
    text = P.joinpath("config.yaml").read_text()
    m = re.search(r"mcp_servers:\n((?:  [a-z0-9_-]+:\n(?:    .*\n?)*?)*)", text)
    if m:
        lanes = re.findall(r"^  ([a-z0-9_-]+):", m.group(1), re.M)
except Exception:
    pass
p("")
p("## 2. MCP Lanes: " + str(len(lanes)))
p(", ".join(sorted(lanes)))

# 3. Providers
provs = []
try:
    text = P.joinpath("config.yaml").read_text()
    m = re.search(r"providers:\n((?:  [a-z0-9_-]+:\n(?:    .*\n?)*?)*)", text)
    if m:
        provs = re.findall(r"^  ([a-z0-9_-]+):", m.group(1), re.M)
except Exception:
    pass
p("")
p("## 3. LLM Providers")
p(", ".join(sorted(provs)))

# 4. Cron jobs
crons = []
cd = P.joinpath("cron")
if cd.exists():
    for f in cd.rglob("*.json"):
        try:
            d = json.loads(f.read_text())
            crons.append(d.get("name", f.stem) + " [" + str(d.get("schedule", "?")) + "]")
        except Exception:
            pass
p("")
p("## 4. Cron Jobs: " + str(len(crons)))
for c in sorted(crons):
    p("- " + c)

# 5. Scripts
sc = [f.name for f in Path("/opt/data/scripts").glob("*.py")] + [f.name for f in Path("/opt/data/scripts").glob("*.sh")]
p("")
p("## 5. Scripts: " + str(len(sc)))
p(", ".join(sorted(sc)))

# 6. Docs
docs = [f.name for f in Path("/opt/data/home/nura-clinical-platform/docs/manuals").glob("*.md")]
projs = [f.name for f in Path("/opt/data/home/nura-clinical-platform/docs/projects").glob("*.md")]
p("")
p("## 6. Docs — manuals " + str(len(docs)) + " + projects " + str(len(projs)))
p("manuals: " + ", ".join(sorted(docs)))
p("projects: " + ", ".join(sorted(projs)))

# 7. Board
p("")
p("## 7. Paperclip board")
p("2 companies (Nuratech.ai + NURA Imaging SaaS DIV-1) · 57+ agents (Atlas CEO, Orion CTO, Iris CMO, Midas CFO…) · issues NUR-1..73 + DIV-1 · execution path LIVE (gateway key patched)")

# 8. Data stores
p("")
p("## 8. Data stores")
p("- Mem0 semantic memory (qdrant embedded) · RAG nura-docs 540 chunks (fastembed, $0) · Obsidian vault (15 notes mirrored) · CME logbook + license registry · self-model (self.json + weekly review)")

content = "\n".join(OUT)
open("/opt/data/profiles/nura/inventory.md", "w").write(content)
shutil.copy("/opt/data/profiles/nura/inventory.md", "/opt/data/Obsidian Vault/NURA-OS/Stack-Inventory.md")
print("inventory.md written: " + str(len(OUT)) + " lines -> vault mirrored")
