window.config = {
  routerBasename: '/',
  customizationService: {},
  extensions: [],
  showStudyList: true,
  maxNumberOfWebWorkers: 8,
  whiteLabeling: {
    createLogoComponentFn: null,
    studyListDateElementNumDays: 30,
  },
  studyListDateFilterNumDays: 30,
  servers: {
    dicomWeb: [
      {
        name: 'NURA PACS — Orthanc',
        wadoUriRoot: 'http://orthanc:8042',
        qidoRoot: 'http://orthanc:8042/dicomweb',
        wadoRoot: 'http://orthanc:8042/dicomweb',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        supportsStudyMetadata: true,
        supportsSeriesMetadata: true,
        supportsMultipleFrames: true,
        requestOptions: {},
      },
    ],
  },
  defaultDataSourceName: 'dicomweb',
  dataSources: [
    {
      friendlyName: 'NURA PACS — Orthanc',
      namespace: 'orthanc.dicomweb',
      sourceName: 'dicomweb',
      configuration: {
        name: 'NURA PACS — Orthanc',
        wadoUriRoot: 'http://orthanc:8042',
        qidoRoot: 'http://orthanc:8042/dicomweb',
        wadoRoot: 'http://orthanc:8042/dicomweb',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        supportsStudyMetadata: true,
        supportsSeriesMetadata: true,
        supportsMultipleFrames: true,
        requestOptions: {},
      },
    },
  ],
  hotkeys: [],
};
